spring.application.name=smartReconciliationAndAudit


jwt.secret=SmartReconciliationSuperSecretKeyForHS256MustBe32CharsMin2024
jwt.expiration=86400000


spring.datasource.url=jdbc:mysql://localhost:3306/reconciliation_audit
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false